### PR TITLE
Fix outgoing qos2 message id bug (#1045)

### LINKED ISSUE #1045: Client terminated with reason: no case clause matching #vmq_msg{}
### Environment

- VerneMQ Version: 1.6.2
- OS: centos7
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior
error logger:
```erlang
2019-01-21 20:09:00.013 [error] <0.29450.2>@vmq_mqtt_fsm:connected:334 Ranch listener {{0,0,0,0},9000} terminated with reason: no case clause matching {vmq_msg,<<55,217,248,92,235,34,154,74,102,128,125,245,72,149,69,45>>,[<<"u_70000026">>,<<"message">>],<<...>>,...} in vmq_mqtt_fsm:connected/2 line 334
```

i check source ：
```erlang
connected(#mqtt_pubcomp{message_id=MessageId}, State) ->
    #state{waiting_acks=WAcks} = State,
    %% qos2 flow
    _ = vmq_metrics:incr_mqtt_pubcomp_received(),
    case maps:get(MessageId, WAcks, not_found) of
        #mqtt_pubrel{} ->
            handle_waiting_msgs(State#state{
                                  waiting_acks=maps:remove(MessageId, WAcks)});
        not_found -> % error or wrong waiting_ack, definitely not well behaving client
            lager:debug("stopped connected session, due to qos2 pubrel missing ~p", [MessageId]),
            _ = vmq_metrics:incr_mqtt_error_invalid_pubcomp(),
            terminate(normal, State)
    end;
```

i don't konw why `WAcks` matched `#vmq_msg{}`

### PR DESCRIPTION
**Pull request by larshesel**
Fixes #1045 

@dergraf note my assumption about `pub_rel`s being send to the session before any normal publishes (without message ids) - I hope this is correct.

### CODE REVIEW

File: apps/vmq_server/src/vmq_mqtt5_fsm.erl [hunk 1]
```diff
@@ -1376,11 +1376,19 @@ handle_messages([{deliver, QoS, Msg} = Obj|Rest], Frames, PubCnt, State, Waiting
...
     %% this is called when a pubrel is retried after a client reconnects
     #state{waiting_acks=WAcks} = State0,
     _ = vmq_metrics:incr(?MQTT5_PUBREL_SENT),
-    State1 = State0#state{waiting_acks=maps:put(MsgId, Frame, WAcks)},
+    %% Assumption: all `deliver_pubrel` messages are delivered from
+    %% the queue when a session is added *before* any other messages.
+    %% The pubrel messages has fixed message-ids and we therefore need
+    %% ensure the first message id assigned to a publish message is
+    %% larger than any of the pubrel messages to avoid conflicts.
+    NextMsgId = lists:max([MsgId + 1, CurrNextMsgId]),
```
Comment (dergraf) [inline apps/vmq_server/src/vmq_mqtt5_fsm.erl]: The `MsgId + 1` could theoretically overrun the message id limit `max(ushort)`.

File: apps/vmq_server/test/vmq_publish_SUITE.erl [hunk 2]
```diff
@@ -459,6 +460,87 @@ publish_c2b_retry_qos2_test(_Config) ->
     ok = expect_alive(Socket),
     ok = gen_tcp:close(Socket).
 
+publish_b2c_ensure_valid_msg_ids_test(Config) ->
```
Comment (dergraf) [inline apps/vmq_server/test/vmq_publish_SUITE.erl]: it would be interesting to test what happens if multiple of such PUBRELs were persisted.

File: apps/vmq_server/src/vmq_mqtt5_fsm.erl (hunk 1 above)
Comment (larshesel) [reply apps/vmq_server/src/vmq_mqtt5_fsm.erl]: Good point.. Will fix that.

File: apps/vmq_server/test/vmq_publish_SUITE.erl (hunk 2 above)
Comment (larshesel) [reply apps/vmq_server/test/vmq_publish_SUITE.erl]: Which test scenario are you thinking about here? I agree more cases could/should be covered, ideally we should property test stuff like this, if possible.

**Comment by larshesel** [comment]
@dergraf I reverted the incorrect fix and implemented a new one where we store the `next_msg_id` in the queue. This, however, revealed another problem (the `in_order_delivery_SUITE` started failing): namely that we do not remember the `msg_id` on outgoing qos2 messages (which didn't yet receive a `pubrec`) when we store waiting acks - so when the client comes back the outgoing publish will set the dup flag to ture and assign a new `msg_id` which is against the spec. So next step is to also remember the msgid used when sending the initial qos2 publish message out when storing the unacked stuff in the queue.

File: apps/vmq_server/src/vmq_mqtt_fsm.erl [hunk 3]
```diff
@@ -539,18 +539,20 @@ check_user(#mqtt_connect{username=User, password=Password} = F, State) ->
         false ->
             case auth_on_register(User, Password, State) of
                 {ok, QueueOpts, #state{peer=Peer, subscriber_id=SubscriberId, clean_session=CleanSession,
-                                       cap_settings=CAPSettings, def_opts=DOpts} = NewState} ->
+                                       cap_settings=CAPSettings, def_opts=DOpts} = State1} ->
                     CoordinateRegs = maps:get(coordinate_registrations, DOpts, ?COORDINATE_REGISTRATIONS),
                     case vmq_reg:register_subscriber(CAPSettings#cap_settings.allow_register, CoordinateRegs, SubscriberId, CleanSession, QueueOpts) of
-                        {ok, SessionPresent, QPid} ->
+                        {ok, #{session_present := SessionPresent,
+                               initial_msg_id := MsgId}, QPid} ->
```
Comment (dergraf) [inline apps/vmq_server/src/vmq_mqtt_fsm.erl]: We could return the `QPid` also as part of the map.

Comment (larshesel) [reply apps/vmq_server/src/vmq_mqtt_fsm.erl]: yeah, I guess that makes sense. Then spec it as a mandatory field in the map.

**Comment by larshesel** [comment]
Since last I:

 - moved the queue pid into the map returned by `vmq_reg:register_subscriber/4`
 - changed the `{deliver, QoS, Msg}` tuple into a record `#deliver{msg_id, qos, msg}` and use this everywhere *except* when enqueueing as we do this across nodes. For some scenarious this means I have to translate between the two, for example in `vmq_queue:enqueue_many` and when draining.

**Comment by larshesel** [comment]
Had to rebase to get CI to run...

**Comment by larshesel** [comment]
@boboxiaodd, I think this is about done - would you be able to test it out?

**Comment by boboxiaodd** [comment]
@larshesel , Great, i clone the master  and  test it now!
